#!/usr/bin/env -S ts-node -r tsconfig-paths/register

// Make sure ts-node is installed
// $ npm install -g ts-node
// Then as follows:
// npx ts-node black-white-sequence.ts foo 50000 > stim-50000.jsonl

import { Solid } from '@stims/index';

//console.error(JSON.stringify(process.argv));
if (process.argv.length < 3) {
  console.error(`Usage: ${process.argv[1]} <title> <nStimuli>`);
  process.exit(-1);
}
const title = process.argv[2];
const nStimuli = +process.argv[3];
const stimuli = new Array(nStimuli);

for (let i = 0; i < nStimuli; i++) {
  const stim = new Solid({ durationMs: 1000, bgColor: i % 2 ? 'black' : 'white' });
  stimuli[i] = stim;
}
console.log(
  JSON.stringify(
    {
      title: title,
      description: `Generated by ${process.argv[1]} ${title} ${nStimuli}`,
      stimuli: stimuli,
    },
    null,
    4
  )
);
