#!/usr/bin/env ts-node
import { filterPrivateProperties } from '../src/shared-utils';
import { FFSine } from '../src/stims/';

if (process.argv.length < 4) {
  console.error(`Usage: ${process.argv[1]} <title> <nStimuli>`);
  process.exit(-1);
}
const title = process.argv[2];
const nStimuli = +process.argv[3];
const stimuli = new Array(nStimuli);

for (let i = 0; i < nStimuli; i++) {
  const stim = new FFSine({
    durationMs: 2000,
    bodyMs: 1500,
    m: 40,
    c: 90 - 10 * (i % 6), // Vary contrasts
    hz: 1 + (i % 4), // Vary frequencies
  });
  stimuli[i] = stim;
}

console.log(
  JSON.stringify(
    {
      title: title,
      description: `Generated by ${process.argv[1]} ${title} ${nStimuli}`,
      stimuli: stimuli,
    },
    filterPrivateProperties,
    4
  )
);
