#!/usr/bin/env ts-node

// Make sure ts-node is installed
// $ npm install -g ts-node
// Then as follows:
// npx ts-node black-white-sequence.ts foo 50000 > stim-50000.jsonl

import { Solid } from '../src/renderer/src/Stims/Stimulus';

//console.error(JSON.stringify(process.argv));
if (process.argv.length < 3) {
  console.error(`Usage: ${process.argv[1]} <name> <nStimuli>`);
  process.exit(-1);
}
const name = process.argv[2];
const nStimuli = +process.argv[3];
const stimuli = new Array(nStimuli);

for (let i = 0; i < nStimuli; i++) {
  const stim = new Solid({ bgColor: i % 2 ? 'black' : 'white' });
  stimuli[i] = stim;
}
console.log(
  JSON.stringify(
    {
      name: name,
      description: `Generated by ${process.argv[1]} ${name} ${nStimuli}`,
      stimuli: stimuli,
    },
    null,
    4
  )
);
